[profile.default]
remappings = [
    "@layerzero-v2/=lib/LayerZero-v2/oapp/contracts/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/protocol/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solmate/=lib/solmate/src/",
]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"

[rpc_endpoints]
scroll_testnet = "https://scroll-sepolia.drpc.org"
arbitrum_sepolia = "https://arbitrum-sepolia.blockpi.network/v1/rpc/public"

[etherscan]
arbitrum_sepolia = {key = "${ARBISCAN_KEY}", url = "https://api-sepolia.arbiscan.io/api"}
scroll_testnet = {key = "${SCROLLSCAN_KEY}", url = "https://api.scrollscan.com/api"}
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
